var cmdtab = {
    "LED": ["C71", "POS", "GROUP", "Action", "UUID", "STU"],
    "PUMP": ["C72", "POS", "GROUP", "Action", "UUID", "STU"],
    "AIRFAN": ["C73", "POS", "GROUP", "Action", "UUID", "STU"],
    "GROUP": ["C74", "POS", "GROUP", "Action", "UUID"],
    "UV": ["C75", "POS", "GROUP", "Action", "UUID", "STU"],
    "CO2": ["C76", "POS", "GROUP", "Action", "UUID"],
    "TEMPERATURE": ["C77", "POS", "GROUP", "Action", "UUID"],
    "RH": ["C78", "POS", "GROUP", "Action", "UUID"],
    "WATERLEVEL": ["C79", "POS", "GROUP", "Action", "UUID"],
    "ELECTRONS": ["C7A", "POS", "GROUP", "Action", "UUID"],
    "PH": ["C7B", "POS", "GROUP", "Action", "UUID"],
    "PWM": ["C7C", "POS", "GROUP", "Action", "UUID"],
    "SETTIME": ["C7D", "POS", "GROUP", "Action", "UUID", "STU"],
    "AUTO": ["C7E", "POS", "GROUP", "Action", "UUID", "STU"],

    "MACADD": ["CE0", "POS", "GROUP", "Action", "UUID", "STU"],
    "IPADD": ["CE1", "POS", "GROUP", "Action", "UUID", "STU"],
    "FWVER": ["CE2", "POS", "GROUP", "Action", "UUID", "STU"],
    "HWVER": ["CE3", "POS", "GROUP", "Action", "UUID", "STU"],
    "TREESCAN": ["C01", "POS", "GROUP", "Action", "UUID", "STU"],
    "TREECOUNT": ["C03", "POS", "GROUP", "Action", "UUID", "STU"],
    "TREELIST": ["C02", "POS", "GROUP", "Action", "UUID", "STU"],
    "DEVTRIG": ["C04", "POS", "GROUP", "Action", "UUID", "STU"],
    "DEVTRIGCOUNT": ["C05", "POS", "GROUP", "Action", "UUID", "STU"],
    "DEVEVENT": ["C06", "POS", "GROUP", "Action", "UUID", "STU"],
    "DEVEVENTCOUNT": ["C07", "POS", "GROUP", "Action", "UUID", "STU"],
    "KEYVER": ["C0F", "POS", "GROUP", "Action", "UUID", "STU"],
    "KEY1EVLIST": ["C10", "POS", "GROUP", "Action", "UUID", "STU"],
    "KEY1EVCOUNT": ["C11", "POS", "GROUP", "Action", "UUID", "STU"],
    "KEY2EVLIST": ["C12", "POS", "GROUP", "Action", "UUID", "STU"],
    "KEY2EVCOUNT": ["C13", "POS", "GROUP", "Action", "UUID", "STU"],
    "DEVINOUT": ["CB0", "POS", "GROUP", "Action", "UUID", "STU"]
}
var subcmdtab = {
    "OFF": 0,
    "ON": 1,
    "LOAD": 2,
    "AUTO": 3,
    "SET": 4,
    "LOW": 5,
    "HI": 6,
    "ALARM": 7,
    "MODELOOP": 8,
    "MODETRIG": 9
}